config/routes.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
Rails.application.routes.draw do
  resources :lists

  root :to => 'home#index'

  match 'activities' => 'home#index'
  match 'admin'      => 'admin/users#index',       :as => :admin
  match 'login'      => 'authentications#new',     :as => :login
  match 'logout'     => 'authentications#destroy', :as => :logout
  match 'profile'    => 'users#show',              :as => :profile
  match 'signup'     => 'users#new',               :as => :signup
  match 'dial'  => 'asterisk#dial',      :as => :dial

  match '/home/options',  :as => :options
  match '/home/toggle',   :as => :toggle
  match '/home/timeline', :as => :timeline
  match '/home/timezone', :as => :timezone
  match '/home/redraw',   :as => :redraw

  resource  :authentication, :except => [:index, :edit]
  resources :comments,       :except => [:new, :show]
  resources :emails,         :only   => [:destroy]
  resources :passwords,      :only   => [:new, :create, :edit, :update]

  resources :accounts, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      match :auto_complete
      get  :redraw
      get  :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get  :contacts
      get  :opportunities
    end
  end

  resources :campaigns, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      match :auto_complete
      get  :redraw
      get  :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get  :leads
      get  :opportunities
    end
  end

  resources :contacts, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      match :auto_complete
      get  :redraw
      get  :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get  :opportunities
    end
  end

  resources :leads, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      match :auto_complete
      get  :redraw
      get  :versions
      get  :autocomplete_account_name
    end
    member do
      get  :convert
      post :discard
      post :subscribe
      post :unsubscribe
      put  :attach
      put  :promote
      put  :reject
    end
  end

  resources :opportunities, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      match :auto_complete
      get  :redraw
      get  :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get  :contacts
    end
  end

  resources :tasks, :id => /\d+/ do
    collection do
      post :filter
      match :auto_complete
    end
    member do
      put  :complete
      put  :uncomplete
    end
  end

  resources :users, :id => /\d+/, :except => [:index, :destroy] do
    member do
      get  :avatar
      get  :password
      put  :upload_avatar
      put  :change_password
      post :redraw
    end
    collection do
      get  :opportunities_overview
      match :auto_complete
    end
  end

  namespace :admin do
    resources :groups

    resources :users do
      collection do
        match :auto_complete
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :field_groups, :except => [:index, :show] do
      collection do
        post :sort
      end
      member do
        get :confirm
      end
    end

    resources :fields do
      collection do
        match :auto_complete
        get   :options
        get   :redraw
        post  :sort
        get   :subform
      end
    end

    resources :tags, :except => [:show] do
      member do
        get :confirm
      end
    end

    resources :fields, :as => :custom_fields
    resources :fields, :as => :core_fields

    resources :settings, :only => :index
    resources :plugins,  :only => :index
  end

end

app/views/layouts/admin/_header.html.haml
%header.header.white-bg
  .toggle-nav
    .icon-reorder.tooltips{"data-original-title" => "Toggle Navigation", "data-placement" => "bottom"}
      %i.fa{class: "fa-reorder"}
  = link_to root_path, :class => "logo" do
    = "CRM"
    %span= "CC"
  .top-nav.notification-row
    %ul.nav.pull-right.top-menu
      - if current_user
        %li.dropdown
          = link_to "#", :class => "dropdown-toggle", "data-toggle" => "dropdown" do
            %span.profile-ava
              = image_tag(path_to_image("avatar1_small.jpg"))
            %span.username #{current_user.name}
            %b.caret
          %ul.dropdown-menu.extended.logout
            .log-arrow-up
            %li.eborder-top
              = link_to profile_path do
                %i.icon_profile
                #{t(:profile)}
            - if current_user.admin?
              %li
                = link_to root_path do
                  %i.icon_folder-alt
                  #{t(:back_to_crm)}
            %li
              = link_to logout_path, :method => :delete do
                %i.icon_key_alt
                #{t(:logout)}
      - else
        %li
          = link_to(t(:login), login_path)
        %li
          = link_to(t(:sign_up), signup_path) if can_signup?
        %li
          = link_to(t(:about), "#", :title => t(:about_ffc), :onclick => "$('#about').dialog({ title: this.title, modal: true }); return false;")

app/views/layouts/admin/application.html.haml
!!!
%html{ :xmlns => "http://www.w3.org/1999/xhtml", "xml:lang" => :en,  :lang => :en }
  %head
    %meta{ "http-equiv" => "Content-Type", :content => "text/html; charset=utf-8" }
    %title= t(:crm_admin_page)
    == <!-- #{controller.controller_name} : #{controller.action_name} -->
    = stylesheet_link_tag :application
    %style= yield :styles

    = javascript_include_tag :application
    = hook(:javascript_includes, self) {}

    %script{:type => "text/javascript"}= yield :javascript
    = csrf_meta_tag

  %body.admin
    %section#container
      = render "layouts/admin/header"
      = render "layouts/tabbed"
      -#= render "layouts/footer"
      %script{:type => "text/javascript"}
        = "crm.base_url = '#{Setting.base_url}';" unless Setting.base_url.blank?
        = get_browser_timezone_offset
        = yield :javascript_epilogue